### PR TITLE
Add GetTransactionsForTxBlockEx API

### PR DESCRIPTION
**Pull request by maxconway**
Add GetTransactionsForTxBlockEx API, along with associated type, and test

The test is fairly minimal, since this is fairly simple code

A future PR might include a test setup with a more developed example network

### CODE REVIEW

**Review by JamesHinshelwood — DISMISSED** [review]
LGTM, thanks :)

**Comment by JamesHinshelwood** [comment]
@maxconway I resolved the conflict because it was easy - I think this will get merged once you press approve?

**Review by maxconway — COMMENTED** [review]
Looks good to me

**Comment by maxconway** [comment]
@rrw-zilliqa, any chance you could approve this? James originally approved it but then we got a merge conflict, which he fixed, so he's the last committer, so he can't re-approve, and I can't approve because I'm the original author

**Comment by JamesHinshelwood** [comment]
Sorry :( That will teach me to try and be helpful :)

**Comment by maxconway** [comment]
I guess there isn't some kind of override to force the merge in this sort of situation?

**Review by JamesHinshelwood — APPROVED** [review]

**Pull request merged**
