### PR TITLE
Reduce iterations in tests

### PR DESCRIPTION
**Pull request by n-hutton**
image

### CODE REVIEW

**Comment by JamesHinshelwood** [comment]
Now that the time for `ZQ2 CI / check` is down to `~16m`, is the motivation for this change weaker?

**Comment by n-hutton** [comment]
> Now that the time for `ZQ2 CI / check` is down to `~16m`, is the motivation for this change weaker?

Only slightly - the CI still bombs out I think if there are more than 2 PRs running in parallel?

**Review by JamesHinshelwood — CHANGES_REQUESTED** [review]
I think we should resolve the CI problems, not reduce the number of tests to work around them.

**Comment by n-hutton** [comment]
> I think we should resolve the CI problems, not reduce the number of tests to work around them.

Yes, that's fair. Closing

**Pull request closed without merging**
