### PR TITLE
Add `gasUsed` to block headers

### LINKED ISSUE #978: Return `gasUsed` in `eth_getBlockByNumber` and `eth_getBlockByHash`
Currently `gasUsed` is set to 0

### PR DESCRIPTION
**Pull request by JamesHinshelwood**
I chose to add the value to block headers, rather than calculate it on the fly. Feel free to discuss if you think the denormalisation is a bad idea.

I also removed a (IMO) misguided `Display` impl for blocks.

Resolves #978.

### CODE REVIEW

**Comment by DrZoltanFazekas** [comment]
> I chose to add the value to block headers, rather than calculate it on the fly. Feel free to discuss if you think the denormalisation is a bad idea.

The `gasUsed` belongs into the block header according to the Ethereum execution layer spec: https://github.com/ethereum/execution-specs/blob/master/src/ethereum/shanghai/blocks.py#L58

What do you mean by denormalisation?

**Comment by JamesHinshelwood** [comment]
> What do you mean by denormalisation?

`gasUsed` can be deterministically derived from other other fields in the block (i.e. the parent's state root and the transactions in the block). I meant it in the sense of https://en.wikipedia.org/wiki/Denormalization.

**Comment by DrZoltanFazekas** [comment]
I don't have an issue with the denormalisation as long as the validators check the correctness of the `gasUsed` stored in the block headers they receive from the block proposer.

**Comment by DrZoltanFazekas** [comment]
What feels unnatural though is that we're breaking what I believed was an intentional separation between the consensus-layer's `BlockHeader` and the execution-layer's `Header` struct, but maybe they were never meant to be clearly separated:
https://github.com/Zilliqa/zq2/blob/main/zilliqa/src/message.rs#L388
https://github.com/Zilliqa/zq2/blob/main/zilliqa/src/api/types/eth.rs#L55

**Comment by DrZoltanFazekas** [comment]
But as you spotted in https://github.com/Zilliqa/zq2/issues/981, the timestamp and more is missing from the block signatures, so we might need to add further fields to the `Header` anyway

**Review by rrw-zilliqa — APPROVED** [review]
Looks good to me :-)

**Pull request merged**
